spring.application.name=portfolio

# Database Setting
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_site
spring.datasource.username=springuser
spring.datasource.password=Wt2Fs7vH
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never
# spring.sql.init.schema-locations=classpath:schema.sql
# spring.sql.init.data-locations=-locations=classpath:data.sql